baseURL: "https://cooble.github.io/"
title: Cooble's Personal Blog
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: About Me
                  url: aboutme/
                  weight: 5
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Personal Dev Blog"
    author: Matěj Černý

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: Cooble Dev Blog
        subtitle: "<span style=\"font-size: 1.2em; line-height: 1;\">☄️</span>&nbsp;C++ | <span style=\"font-size: 1.2em; line-height: 1;\">⚙️</span>&nbsp;Game & Engines | <span style=\"font-size: 1.2em; line-height: 1;\">☕</span>&nbsp;Java | <span style=\"font-size: 1.1em; line-height: 1;\">電</span>&nbsp;Electronics"
        buttons:
            - name: About
              url: aboutme
            - name: Blog
              url: posts

    socialIcons:
        - name: github
          url: "https://github.com/cooble"
        - name: Discord
          url: "https://discord.gg/thecherno"
        - name: email
          url: "mailto:matej.cerny.dev@gmail.com"

markup:
    goldmark:
        renderer:
            unsafe: true

privacy:
    youtube:
        disabled: false
        privacyEnhanced: true